version: "2"
linters:
  enable:
    - durationcheck
    - errorlint
    - loggercheck
    - sloglint
    - tagliatelle
    - unconvert
  settings:
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          env: upperSnake
          envconfig: upperSnake
          json: snake
          mapstructure: kebab
          toml: camel
          xml: camel
          yaml: camel
        use-field-name: true

    staticcheck:
      checks:
        - -ST1006
        - -QF1001
        - -QF1002
        - -QF1003
        - -QF1004
        - -QF1008
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: repository/ingested_data_indexes_repository.go
        text: should be called, not discarded, to avoid a context leak
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
