linters:
  enable:
    - errorlint
    - loggercheck
    - durationcheck
    - sloglint
    - unconvert

issues:
  exclude-rules:
    - path: repository/ingested_data_indexes_repository.go
      text: "should be called, not discarded, to avoid a context leak"
