name: Test Back-end

on: [workflow_call]

jobs:
  test_backend:
    name: Test Back-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
