name: Deploy Production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_backend:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    uses: ./.github/workflows/backend_test_workflow.yaml

  build_and_deploy_backend:
    needs: test_backend
    uses: ./.github/workflows/backend_deploy_workflow.yaml
    permissions:
      contents: read
      id-token: "write" # needed for using open id token to authenticate with GCP services
    with:
      environment: "production"
      version: ${{ github.ref_name }}
    secrets:
      segment_write_key_opensource: ${{ secrets.SEGMENT_WRITE_KEY_OPENSOURCE }}

  publish_readme:
    needs: test_backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download OpenAPI specification artifacts
        uses: actions/download-artifact@v4
        with:
          name: marble-api-openapi
          path: /tmp/openapis
          retention-days: 1

      - name: Publish Marble API OpenAPI
        uses: readmeio/rdme@v10
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: openapi upload --version=v1.0.0 --slug=marble-api /tmp/openapis/marble-api-v1.yml
