name: Deploy Production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_backend:
    uses: ./.github/workflows/backend_test_workflow.yaml

  build_and_deploy_backend:
    needs: test_backend
    uses: ./.github/workflows/backend_deploy_workflow.yaml
    with:
      environment: "production"
      version: ${{ github.ref_name }}
