name: Deploy Production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_backoffice:
    uses: ./.github/workflows/backoffice_test_workflow.yaml

  build_and_deploy_backoffice:
    needs: test_backoffice
    uses: ./.github/workflows/backoffice_deploy_workflow.yaml
    with:
      environment: "production"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_PRODUCTION }}

  test_backend:
    uses: ./.github/workflows/backend_test_workflow.yaml

  build_and_deploy_backend:
    needs: test_backend
    uses: ./.github/workflows/backend_deploy_workflow.yaml
    with:
      environment: "production"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_PRODUCTION }}
