name: Sync OpenAPI definition to ReadMe

on:
  push:
    branches:
      - master
    paths:
      - specs/public-api.yaml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Validate OpenAPI
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate ./specs/public-api.yaml

      - name: Sync OpenAPI
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./specs/public-api.yaml --key=${{ secrets.README_API_KEY }} --id=MARBLE_PUBLIC_API
