package models

type Permission string

const (
	DECISION_READ                     Permission = "DECISION_READ"
	DECISION_CREATE                   Permission = "DECISION_CREATE"
	PHANTOM_DECISION_CREATE           Permission = "PHANTOM_DECISION_CREATE"
	INGESTION                         Permission = "INGESTION"
	SCENARIO_READ                     Permission = "SCENARIO_READ"
	SCENARIO_CREATE                   Permission = "SCENARIO_CREATE"
	SCENARIO_PUBLISH                  Permission = "SCENARIO_PUBLISH"
	DATA_MODEL_READ                   Permission = "DATA_MODEL_READ"
	DATA_MODEL_WRITE                  Permission = "DATA_MODEL_WRITE"
	APIKEY_READ                       Permission = "APIKEY_READ"
	APIKEY_CREATE                     Permission = "APIKEY_CREATE"
	ANALYTICS_READ                    Permission = "ANALYTICS_READ"
	ORGANIZATIONS_LIST                Permission = "ORGANIZATIONS_LIST"
	ORGANIZATIONS_CREATE              Permission = "ORGANIZATIONS_CREATE"
	ORGANIZATIONS_UPDATE              Permission = "ORGANIZATIONS_UPDATE"
	ORGANIZATIONS_DELETE              Permission = "ORGANIZATIONS_DELETE"
	USER_CREATE                       Permission = "USER_CREATE"
	MARBLE_USER_READ                  Permission = "MARBLE_USER_READ"
	MARBLE_USER_CREATE                Permission = "MARBLE_USER_CREATE"
	MARBLE_USER_UPDATE                Permission = "MARBLE_USER_UPDATE"
	MARBLE_USER_DELETE                Permission = "MARBLE_USER_DELETE"
	ANY_ORGANIZATION_ID_IN_CONTEXT    Permission = "ANY_ORGANIZATION_ID_IN_CONTEXT"
	CUSTOM_LISTS_READ                 Permission = "CUSTOM_LISTS_READ"
	CUSTOM_LISTS_EDIT                 Permission = "CUSTOM_LISTS_EDIT"
	MARBLE_USER_LIST                  Permission = "MARBLE_USER_LIST"
	CASE_READ_WRITE                   Permission = "CASE_READ_WRITE"
	INBOX_EDITOR                      Permission = "INBOX_EDITOR"
	LICENSE_LIST                      Permission = "LICENSE_LIST"
	LICENSE_CREATE                    Permission = "LICENSE_CREATE"
	LICENSE_UPDATE                    Permission = "LICENSE_UPDATE"
	WEBHOOK_EVENT                     Permission = "WEBHOOK_EVENT"
	WEBHOOK                           Permission = "WEBHOOK"
	READ_SNOOZES                      Permission = "READ_SNOOZES"
	CREATE_SNOOZE                     Permission = "CREATE_SNOOZE"
	TAG_READ                          Permission = "TAG_READ"
	TAG_CREATE                        Permission = "TAG_CREATE"
	TAG_UPDATE                        Permission = "TAG_UPDATE"
	TAG_DELETE                        Permission = "TAG_DELETE"
	SCREENING_WHITELIST_READ          Permission = "SCREENING_WHITELIST_READ"
	SCREENING_WHITELIST_WRITE         Permission = "SCREENING_WHITELIST_WRITE"
	SCREENING_FREEFORM_SEARCH         Permission = "SCREENING_FREEFORM_SEARCH"
	CONTINUOUS_SCREENING_CONFIG_READ  Permission = "CONTINUOUS_SCREENING_CONFIG_READ"
	CONTINUOUS_SCREENING_CONFIG_WRITE Permission = "CONTINUOUS_SCREENING_CONFIG_WRITE"
	CONTINUOUS_SCREENING_HIT_READ     Permission = "CONTINUOUS_SCREENING_HIT_READ"
	CONTINUOUS_SCREENING_HIT_WRITE    Permission = "CONTINUOUS_SCREENING_HIT_WRITE"
	CONTINUOUS_SCREENING_HIT_DISMISS  Permission = "CONTINUOUS_SCREENING_HIT_DISMISS"
	CONTINUOUS_SCREENING_OBJECT_READ  Permission = "CONTINUOUS_SCREENING_OBJECT_READ"
	CONTINUOUS_SCREENING_OBJECT_WRITE Permission = "CONTINUOUS_SCREENING_OBJECT_WRITE"
	ANNOTATION_DELETE                 Permission = "ANNOTATION_DELETE"
	ANNOTATION_RISK_TAG_WRITE         Permission = "ANNOTATION_RISK_TAG_WRITE"
	ORG_IMPORT_ARCHETYPE_READ         Permission = "ORG_IMPORT_ARCHETYPE_READ"
	ORG_IMPORT_INTO_EXISTING          Permission = "ORG_IMPORT_INTO_EXISTING"
	ORG_EXPORT                        Permission = "ORG_EXPORT"
	SCORING_UPDATE_SETTINGS           Permission = "SCORING_UPDATE_SETTINGS"
	SCORING_UPDATE_RULESETS           Permission = "SCORING_UPDATE_RULESETS"
	SCORING_OVERRIDE_SCORE            Permission = "SCORING_OVERRIDE_SCORE"
	MANAGE_ROLES                      Permission = "MANAGE_ROLES"
)

var ValidPermissions = []Permission{
	DECISION_READ,
	DECISION_CREATE,
	PHANTOM_DECISION_CREATE,
	INGESTION,
	SCENARIO_READ,
	SCENARIO_CREATE,
	SCENARIO_PUBLISH,
	DATA_MODEL_READ,
	DATA_MODEL_WRITE,
	APIKEY_READ,
	APIKEY_CREATE,
	ANALYTICS_READ,
	ORGANIZATIONS_LIST,
	ORGANIZATIONS_CREATE,
	ORGANIZATIONS_UPDATE,
	ORGANIZATIONS_DELETE,
	USER_CREATE,
	MARBLE_USER_READ,
	MARBLE_USER_CREATE,
	MARBLE_USER_UPDATE,
	MARBLE_USER_DELETE,
	ANY_ORGANIZATION_ID_IN_CONTEXT,
	CUSTOM_LISTS_READ,
	CUSTOM_LISTS_EDIT,
	MARBLE_USER_LIST,
	CASE_READ_WRITE,
	INBOX_EDITOR,
	LICENSE_LIST,
	LICENSE_CREATE,
	LICENSE_UPDATE,
	WEBHOOK_EVENT,
	WEBHOOK,
	READ_SNOOZES,
	CREATE_SNOOZE,
	TAG_READ,
	TAG_CREATE,
	TAG_UPDATE,
	TAG_DELETE,
	SCREENING_WHITELIST_READ,
	SCREENING_WHITELIST_WRITE,
	SCREENING_FREEFORM_SEARCH,
	CONTINUOUS_SCREENING_CONFIG_READ,
	CONTINUOUS_SCREENING_CONFIG_WRITE,
	CONTINUOUS_SCREENING_HIT_READ,
	CONTINUOUS_SCREENING_HIT_WRITE,
	CONTINUOUS_SCREENING_HIT_DISMISS,
	CONTINUOUS_SCREENING_OBJECT_READ,
	CONTINUOUS_SCREENING_OBJECT_WRITE,
	ANNOTATION_DELETE,
	ANNOTATION_RISK_TAG_WRITE,
	ORG_IMPORT_ARCHETYPE_READ,
	ORG_IMPORT_INTO_EXISTING,
	ORG_EXPORT,
	SCORING_UPDATE_SETTINGS,
	SCORING_UPDATE_RULESETS,
	SCORING_OVERRIDE_SCORE,
	MANAGE_ROLES,
}
