package models

var VIEWER_PERMISSIONS = []Permission{
	ANALYTICS_READ,
	DECISION_READ,
	SCENARIO_READ,
	DATA_MODEL_READ,
	CUSTOM_LISTS_READ,
	CASE_READ_WRITE,
	WEBHOOK_EVENT,
	READ_SNOOZES,
	CREATE_SNOOZE,
	TAG_READ,
	MARBLE_USER_READ,
	MARBLE_USER_LIST,
	MARBLE_USER_UPDATE,
}

var (
	BUILDER_PERMISSIONS   = append(VIEWER_PERMISSIONS, SCENARIO_CREATE, CUSTOM_LISTS_EDIT)
	PUBLISHER_PERMISSIONS = append(BUILDER_PERMISSIONS, SCENARIO_PUBLISH)
	ADMIN_PERMISSIONS     = append(
		PUBLISHER_PERMISSIONS,
		APIKEY_READ,
		APIKEY_CREATE,
		DATA_MODEL_WRITE,
		DECISION_CREATE, // Used to validate permission to start a scheduled execution of a scenario
		INGESTION,
		MARBLE_USER_CREATE,
		MARBLE_USER_DELETE,
		INBOX_EDITOR,
		WEBHOOK,
		TAG_CREATE,
		TAG_UPDATE,
		TAG_DELETE,
		ORGANIZATIONS_UPDATE,
		ANNOTATION_DELETE,
	)
)

var ROLES_PERMISSIOMS = map[Role][]Permission{
	NO_ROLE:   {},
	VIEWER:    VIEWER_PERMISSIONS,
	BUILDER:   BUILDER_PERMISSIONS,
	PUBLISHER: PUBLISHER_PERMISSIONS,
	ADMIN:     ADMIN_PERMISSIONS,
	API_CLIENT: {
		SCENARIO_READ, // Used to validate the scenario being executed in the decision usecase
		DECISION_READ,
		DECISION_CREATE,
		PHANTOM_DECISION_CREATE, // Necessary because a permission check is embedded in the phantom decision usecase
		INGESTION,
		WEBHOOK_EVENT, // Necessary because a permission check is embedded in the webhooks events usecase
		CASE_READ_WRITE,
		READ_SNOOZES,
		CREATE_SNOOZE,
		SANCTION_CHECK_WHITELIST_READ,
		SANCTION_CHECK_WHITELIST_WRITE,
		SANCTION_CHECK_FREEFORM_SEARCH,
	},
	TRANSFER_CHECK_API_CLIENT: {
		TRANSFER_READ,
		TRANSFER_CREATE,
		TRANSFER_UPDATE,
		DECISION_CREATE,
		PHANTOM_DECISION_CREATE,
	},
	TRANSFER_CHECK_USER: {
		TRANSFER_READ,
		TRANSFER_UPDATE,
		PARTNER_READ,
		TRANSFER_ALERT_READ,
		TRANSFER_ALERT_UPDATE,
		TRANSFER_ALERT_CREATE,
	},
	MARBLE_ADMIN: append(
		ADMIN_PERMISSIONS,
		ORGANIZATIONS_LIST,
		ORGANIZATIONS_CREATE,
		ORGANIZATIONS_UPDATE,
		ORGANIZATIONS_DELETE,
		ANY_ORGANIZATION_ID_IN_CONTEXT,
		ANY_PARTNER_ID_IN_CONTEXT,
		PARTNER_LIST,
		PARTNER_READ,
		PARTNER_CREATE,
		PARTNER_UPDATE,
		LICENSE_LIST,
		LICENSE_CREATE,
		LICENSE_UPDATE,
	),
}
