package models

var VIEWER_PERMISSIONS = []Permission{
	DECISION_READ,
	SCENARIO_READ,
	DATA_MODEL_READ,
	CUSTOM_LISTS_READ,
}

var BUILDER_PERMISSIONS = append(VIEWER_PERMISSIONS, SCENARIO_CREATE, CUSTOM_LISTS_CREATE)
var PUBLISHER_PERMISSIONS = append(BUILDER_PERMISSIONS, SCENARIO_PUBLISH)
var ADMIN_PERMISSIONS = append(PUBLISHER_PERMISSIONS, USER_CREATE, APIKEY_READ)

var ROLES_PERMISSIOMS = map[Role][]Permission{
	NO_ROLE:    {},
	VIEWER:     VIEWER_PERMISSIONS,
	BUILDER:    BUILDER_PERMISSIONS,
	PUBLISHER:  PUBLISHER_PERMISSIONS,
	ADMIN:      ADMIN_PERMISSIONS,
	API_CLIENT: {SCENARIO_READ, DECISION_READ, DECISION_CREATE, INGESTION, DATA_MODEL_READ, CUSTOM_LISTS_READ, CUSTOM_LISTS_CREATE},
	MARBLE_ADMIN: append(
		ADMIN_PERMISSIONS,
		DECISION_CREATE,
		INGESTION,
		ORGANIZATIONS_LIST,
		ORGANIZATIONS_CREATE,
		ANY_ORGANIZATION_ID_IN_CONTEXT,
		MARBLE_USER_CREATE,
		MARBLE_USER_DELETE,
		CUSTOM_LISTS_READ,
		CUSTOM_LISTS_CREATE,
		DATA_MODEL_WRITE,
	),
}
